version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: "http://localhost:8000"
    ports:
      - "5173:80"
    restart: unless-stopped